# This environment installs the latests released version of hydromt-sfincs,
# including some dependencies to run the examples 
name: hydromt-wflow-sfincs

channels:
  - conda-forge

dependencies:
  - cartopy>=0.20
  - descartes
  - hydromt==0.9.1
  - hydromt_wflow==0.4.1
  - jupyterlab
  - matplotlib
  - pip
  - python=3.10
  - requests
  - pip:
    - gwwapi 
    - git+https://github.com/Deltares/hydromt_sfincs.git@1542ebca3f4e3f876773a4f2da3d87e6ff49e417 # V1.0.2.dev with hydromt 0.9 support
